
/**
* CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* Thursday, June 3, 2021 at 3:03:05 PM Western European Summer Time
*/


//Counter IDL
public interface CounterOperations 
{
  int value ();
  void inc ();
  void desc ();
} // interface CounterOperations
