
/**
* AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlarmHelper.type ();
  }

}
