
/**
* AlarmPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
public class AlarmPOATie extends AlarmPOA
{

  // Constructors

  public AlarmPOATie ( AlarmOperations delegate ) {
      this._impl = delegate;
  }
  public AlarmPOATie ( AlarmOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public AlarmOperations _delegate() {
      return this._impl;
  }
  public void _delegate (AlarmOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int h ()
  {
    return _impl.h();
  } // heur

  public int min ()
  {
    return _impl.min();
  } // minute

  public void LocalTime ()
  {
    _impl.LocalTime();
  } // LocalTimer

  public void setAlarm (int h, int min)
  {
    _impl.setAlarm(h, min);
  } // activer

  private AlarmOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AlarmPOATie
