
/**
* AlarmOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
public interface AlarmOperations 
{
  int h ();
  int min ();
  void LocalTime ();
  void setAlarm (int h, int min);
} // interface AlarmOperations
