
/**
* Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
public interface Alarm extends AlarmOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Alarm
