
/**
* AlarmHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
abstract public class AlarmHelper
{
  private static String  _id = "IDL:Alarm:1.0";

  public static void insert (org.omg.CORBA.Any a, Alarm that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Alarm extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AlarmHelper.id (), "Alarm");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Alarm read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlarmStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Alarm value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Alarm narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Alarm)
      return (Alarm)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AlarmStub stub = new _AlarmStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Alarm unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Alarm)
      return (Alarm)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AlarmStub stub = new _AlarmStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
