
/**
* AlarmPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alarm.idl
* dimanche 7 juin 2020
*/


//Alarm.idl
public abstract class AlarmPOA extends org.omg.PortableServer.Servant
 implements AlarmOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_h", new java.lang.Integer (0));
    _methods.put ("_get_min", new java.lang.Integer (1));
    _methods.put ("LocalTime", new java.lang.Integer (2));
    _methods.put ("setAlarm", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Alarm/_get_heur
       {
         int $result = (int)0;
         $result = this.h ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Alarm/_get_minute
       {
         int $result = (int)0;
         $result = this.min ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Alarm/LocalTime
       {
         this.LocalTime ();
         out = $rh.createReply();
         break;
       }

       case 3:  // Alarm/setAlarm
       {
         int heur = in.read_long ();
         int minute = in.read_long ();
         this.setAlarm (h, min);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Alarm:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Alarm _this() 
  {
    return AlarmHelper.narrow(
    super._this_object());
  }

  public Alarm _this(org.omg.CORBA.ORB orb) 
  {
    return AlarmHelper.narrow(
    super._this_object(orb));
  }


} // class AlarmPOA
