
/**
* CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* Monday, June 7, 2021 at 11:34:56 PM Western European Summer Time
*/


//Counter IDL
public interface CounterOperations 
{
  int value ();
  void inc ();
  void desc ();
} // interface CounterOperations
