
/**
* HorlogeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* Thursday, June 10, 2021 at 10:33:17 AM Western European Summer Time
*/

public interface HorlogeOperations 
{
  String heure ();
  void setGMT ();
  void setHeureEte ();
} // interface HorlogeOperations
