
/**
* Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* Thursday, June 10, 2021 at 10:33:17 AM Western European Summer Time
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
